crisprai_dependencies <- c("python==2.7.18",
                           "biopython==1.68",
                           "blas==1.1",
                           "bx-python==0.7.3",
                           "bzip2==1.0.8",
                           "curl==7.71.1",
                           "freetype==2.10.4",
                           "jpeg==9b",
                           "krb5==1.18.2",
                           "libblas==3.8.0",
                           "libcblas==3.8.0",
                           "libcxx==12.0.1",
                           "libdeflate==1.0",
                           "libedit==3.1.20191231",
                           "libffi==3.3",
                           "libgfortran==3.0.0",
                           "liblapack==3.8.0",
                           "libopenblas==0.3.10",
                           "libpng==1.6.37",
                           "libssh2==1.9.0",
                           "libtiff==4.1.0",
                           "llvm-openmp==12.0.1",
                           "lz4-c==1.9.2",
                           "mmtf-python==1.0.2",
                           "msgpack-python==0.6.1",
                           "ncurses==6.2",
                           "numpy==1.11.3",
                           "olefile==0.46",
                           "openblas==0.2.18",
                           "openssl==1.1.1h",
                           "pillow==6.2.1",
                           "pip==19.3.1",
                           "pysam==0.15.3",
                           "python_abi==2.7",
                           "readline==8.0",
                           "reportlab==3.5.26",
                           "scikit-learn==0.17.1",
                           "scipy==0.18.1",
                           "setuptools==44.0.0",
                           "sqlite==3.33.0",
                           "tk==8.6.10",
                           "viennarna==2.4.18",
                           "wheel==0.36.2",
                           "xz==5.2.5",
                           "zlib==1.2.11",
                           "zstd==1.4.4")
crisprai_dependencies_pip <- c("pandas==0.15.0")


env_crisprai <- BasiliskEnvironment(envname="crisprai_basilisk",
                                    pkgname="crisprScore",
                                    packages=crisprai_dependencies,
                                    channels = c("main",
                                                 "anaconda",
                                                 "bioconda",
                                                 "conda-forge"),
                                    pip=crisprai_dependencies_pip)

